### ISSUE TITLE
la co-latitude et la co-longitude

### ISSUE THREAD

**Issue by yafeunteun** [yafeunteun/kaggle-plasticc-astronomical-classification#2]
Devons nous supprimer la co-latitude et la co-longitude, puisque ils sont corrélés avec la longitude et la latitude.

**Comment by yafeunteun** [comment]
Il faudrait étudier ça de plus près et faire un test de corrélation entre les deux variables (type Kendall ou Spearman) pour en être certain.

**Comment by frankl1** [comment]
On a eu la réponse aujourd'hui, c'est corrélé
